### ISSUE TITLE
Opracowanie modelu domenowego dla konwersacji i konwersacji grupowych  

### ISSUE THREAD

**Issue by Sylwekqaz** [chat-sggw/server#3]
Tutaj jest analiza funkcjonalna: https://github.com/chat-sggw/docs/wiki/Analiza-funkcjonalna
na jej podstawie musicie opracować model domenowy dla konwersacji i konwersacji grupowych

**Comment by DTJanicka** [comment]
Na kiedy zostanie to wykonane?

**Comment by ka-res** [comment]
Jakiś start jest. Wrzucone encje i DTO, pojawiły się klasy i interfejsy w warstwie serisu. Dodałem referencję do System.Device.Location, żeby sensownie operować na danych geo.
Dajcie znać, jak to się ma do efektu założonego.

**Comment by ka-res** [comment]
Temat zrealizowany z @Sylwekqaz
